name: Launch rocket

on:
  issue_comment:
    types:
      - created

jobs:
  launch-rocket:
    if: github.event.comment.body == 'launch'
    name: Launch rocket
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Launch rocket
        run: |
          echo "${{ toJSON(github.event) }}"
          gh pr comment ${{ github.event.issue.number }} --body "Launching the rocket ðŸš€"
